// <auto-generated />
namespace SPA_Practice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SubjectCollectionIsAdded3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubjectCollectionIsAdded3));
        
        string IMigrationMetadata.Id
        {
            get { return "201912061500141_SubjectCollectionIsAdded3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
